### ISSUE TITLE
Use of fstrings (Python)

### ISSUE THREAD

**Issue by afonsofilhozup** [ZupIT/horusec-engine#39]
**What happened**:
In Python 3.6 the [fstrings](https://www.python.org/dev/peps/pep-0498/) feature was added, when using it in the PostgreSQL connection, the HorusecEngine tool identifies an information leak but this is incorrect because `password` is a variable:

```
Language: Leaks
Severity: CRITICAL
Line: xx
Column: xx
SecurityTool: HorusecEngine
Confidence: MEDIUM
File: /path/to/file.py
Code: return f"postgresql://{user}:{password}@{host}/{database}"
Details: Password found in a hardcoded URL
A password was found in a hardcoded URL, this can lead to not only the leak of this password but also a failure point to some more sophisticated CSRF and SSRF attacks. Check CWE-352 (https://cwe.mitre.org/data/definitions/352.html) and CWE-918 (https://cwe.mitre.org/data/definitions/918.html) for more details.
Type: Vulnerability
ReferenceHash: xxxxxxxxxxxxx
```

**What you expected to happen**:
The HorusecEngine tool can identify variables in an fstring in Python code.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a file with this content:
```python
def get_postgres_uri(host: str, password: str, user: str, database: str)-> str:
    return f"postgresql://{user}:{password}@{host}/{database}"
```
2. Run `horusec start -p="./" -e="true"`.

**Environment**:
- Horusec version: v2.5.0 / dist normal
- Operating System: Ubuntu 20.04

**Comment by iancardosozup** [comment]
Unfortunately this is something we can't fix, as a SAST tools there is some vulnerabilities we still can't ensure wether is as hardcoded password or not. We're working on semantic analyisis as you can check on or [roadmap](https://github.com/ZupIT/horusec/blob/main/ROADMAP.md) (english version in WIP) to fix this problem and many others. 
Thanks for the feedback and feel free to ask as many questions as you want.
